{
    "name": "Hotel Base",
    "version": "19.0.1.0.0",
    "summary": "Core hotel configuration for properties, buildings, floors, room categories, amenities, taxes, and seasons",
    "category": "Hospitality",
    "license": "LGPL-3",
    "depends": [
        "base",
        "mail",
        "product",
        "account",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/cron.xml",
        "views/res_company_views.xml",
        "views/hotel_property_views.xml",
        "views/hotel_building_views.xml",
        "views/hotel_floor_views.xml",
        "views/hotel_room_category_views.xml",
        "views/hotel_amenity_views.xml",
        "views/hotel_tax_views.xml",
        "views/hotel_season_views.xml",
        "views/menu_views.xml",
    ],
    "demo": [
        "demo/hotel_base_demo.xml",
    ],
    "assets": {
        "web.assets_backend": [],
    },
    "application": True,
    "installable": True,
}